spring:
  application:
    name: auth-service
  datasource:
    url: ${JDBC_URL}
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ""
      timeout: 60000
---
security:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 3600000 # Expiration time in milliseconds (1 hour here)
    refresh-expiration: 604800000 # 7 days
---
server:
  port: ${SERVER_PORT}
  http2:
    enabled: true
  ssl:
    certificate: ${SSL_PUB_CERT_PATH}
    certificate-private-key: ${SSL_PRIV_CERT_PATH}
    enabled: true
  error:
    include-message: always
  servlet:
    context-path: /auth-service
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html
